# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ipam_pb2 as ipam__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ipam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeAgentStub(object):
    """Сервис агента на узле (клиентское приложение - эмуляция коммутатора)
    IPAM сервер подключается к этому сервису для получения/изменения маршрутов
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoutes = channel.unary_unary(
                '/ipam.NodeAgent/GetRoutes',
                request_serializer=ipam__pb2.GetRoutesRequest.SerializeToString,
                response_deserializer=ipam__pb2.GetRoutesResponse.FromString,
                _registered_method=True)
        self.ApplyChanges = channel.unary_unary(
                '/ipam.NodeAgent/ApplyChanges',
                request_serializer=ipam__pb2.ApplyChangesRequest.SerializeToString,
                response_deserializer=ipam__pb2.ApplyChangesResponse.FromString,
                _registered_method=True)


class NodeAgentServicer(object):
    """Сервис агента на узле (клиентское приложение - эмуляция коммутатора)
    IPAM сервер подключается к этому сервису для получения/изменения маршрутов
    """

    def GetRoutes(self, request, context):
        """Получить текущие маршруты с узла
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyChanges(self, request, context):
        """Применить изменения к маршрутам
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutes,
                    request_deserializer=ipam__pb2.GetRoutesRequest.FromString,
                    response_serializer=ipam__pb2.GetRoutesResponse.SerializeToString,
            ),
            'ApplyChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyChanges,
                    request_deserializer=ipam__pb2.ApplyChangesRequest.FromString,
                    response_serializer=ipam__pb2.ApplyChangesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ipam.NodeAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ipam.NodeAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeAgent(object):
    """Сервис агента на узле (клиентское приложение - эмуляция коммутатора)
    IPAM сервер подключается к этому сервису для получения/изменения маршрутов
    """

    @staticmethod
    def GetRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipam.NodeAgent/GetRoutes',
            ipam__pb2.GetRoutesRequest.SerializeToString,
            ipam__pb2.GetRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipam.NodeAgent/ApplyChanges',
            ipam__pb2.ApplyChangesRequest.SerializeToString,
            ipam__pb2.ApplyChangesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
