# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipam.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ipam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nipam.proto\x12\x04ipam\"\x93\x01\n\x05Route\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x11\n\tinterface\x18\x02 \x01(\t\x12#\n\nroute_type\x18\x03 \x01(\x0e\x32\x0f.ipam.RouteType\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x1f\n\x02\x61\x66\x18\x06 \x01(\x0e\x32\x13.ipam.AddressFamily\"3\n\x10GetRoutesRequest\x12\x1f\n\x02\x61\x66\x18\x01 \x01(\x0e\x32\x13.ipam.AddressFamily\"A\n\x11GetRoutesResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x1b\n\x06routes\x18\x02 \x03(\x0b\x32\x0b.ipam.Route\"Q\n\x10RouteInstruction\x12!\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x11.ipam.RouteAction\x12\x1a\n\x05route\x18\x02 \x01(\x0b\x32\x0b.ipam.Route\"C\n\x13\x41pplyChangesRequest\x12,\n\x0cinstructions\x18\x01 \x03(\x0b\x32\x16.ipam.RouteInstruction\"W\n\x11InstructionResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x1a\n\x05route\x18\x03 \x01(\x0b\x32\x0b.ipam.Route\"Q\n\x14\x41pplyChangesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12(\n\x07results\x18\x02 \x03(\x0b\x32\x17.ipam.InstructionResult*X\n\tRouteType\x12\x1a\n\x16ROUTE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14ROUTE_TYPE_CONNECTED\x10\x01\x12\x15\n\x11ROUTE_TYPE_STATIC\x10\x02*=\n\rAddressFamily\x12\x12\n\x0e\x41\x46_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x41\x46_IPV4\x10\x01\x12\x0b\n\x07\x41\x46_IPV6\x10\x02*Z\n\x0bRouteAction\x12\x1c\n\x18ROUTE_ACTION_UNSPECIFIED\x10\x00\x12\x14\n\x10ROUTE_ACTION_ADD\x10\x01\x12\x17\n\x13ROUTE_ACTION_DELETE\x10\x02\x32\x90\x01\n\tNodeAgent\x12<\n\tGetRoutes\x12\x16.ipam.GetRoutesRequest\x1a\x17.ipam.GetRoutesResponse\x12\x45\n\x0c\x41pplyChanges\x12\x19.ipam.ApplyChangesRequest\x1a\x1a.ipam.ApplyChangesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTETYPE']._serialized_start=614
  _globals['_ROUTETYPE']._serialized_end=702
  _globals['_ADDRESSFAMILY']._serialized_start=704
  _globals['_ADDRESSFAMILY']._serialized_end=765
  _globals['_ROUTEACTION']._serialized_start=767
  _globals['_ROUTEACTION']._serialized_end=857
  _globals['_ROUTE']._serialized_start=21
  _globals['_ROUTE']._serialized_end=168
  _globals['_GETROUTESREQUEST']._serialized_start=170
  _globals['_GETROUTESREQUEST']._serialized_end=221
  _globals['_GETROUTESRESPONSE']._serialized_start=223
  _globals['_GETROUTESRESPONSE']._serialized_end=288
  _globals['_ROUTEINSTRUCTION']._serialized_start=290
  _globals['_ROUTEINSTRUCTION']._serialized_end=371
  _globals['_APPLYCHANGESREQUEST']._serialized_start=373
  _globals['_APPLYCHANGESREQUEST']._serialized_end=440
  _globals['_INSTRUCTIONRESULT']._serialized_start=442
  _globals['_INSTRUCTIONRESULT']._serialized_end=529
  _globals['_APPLYCHANGESRESPONSE']._serialized_start=531
  _globals['_APPLYCHANGESRESPONSE']._serialized_end=612
  _globals['_NODEAGENT']._serialized_start=860
  _globals['_NODEAGENT']._serialized_end=1004
# @@protoc_insertion_point(module_scope)
